---
- name: General setup for all VMs
  hosts: all
  tasks:
    # Step 4: Register SSH Keys
    - name: Register SSH keys from team members
      ansible.posix.authorized_key:
        user: " {{ ansible_user }} "
        state: present
        key: "{{ lookup('file', item) }}"
      loop: "{{ query('fileglob', '/vagrant/ssh-keys/*.pub') }}"

    # Step 5: Disable SWAP
    - name: Disable swap in running system
      become: true
      ansible.builtin.shell: swapoff -a

    - name: Remove swap entry from /etc/fstab
      become: true
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '.*swap.*'
        state: absent

    # Step 6: br_netfilter
    - name: Create k8s.conf for module loading
      become: true
      ansible.builtin.copy:
        content: |
          overlay
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf
        mode: '0644'

    - name: Load br_netfilter module
      become: true
      community.general.modprobe:
        name: br_netfilter
        state: present

    - name: Load overlay module
      become: true
      community.general.modprobe:
        name: overlay
        state: present

    # Step 7: Enable IPv4 forwarding
    - name: Enable net.ipv4.ip_forward
      become: true
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: true

    - name: Enable net.bridge.bridge-nf-call-iptables
      become: true
      ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        state: present
        reload: true

    - name: Enable net.bridge.bridge-nf-call-ip6tables
      become: true
      ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: '1'
        state: present
        reload: true

    # Step 8: Manage /etc/hosts
    - name: Add cluster nodes to /etc/hosts
      become: true
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          192.168.56.100 ctrl
          {% for i in range(1, num_workers|int + 1) %}
          192.168.56.{{ 100 + i }} node-{{ i }}
          {% endfor %}
        marker: "# {mark} ANSIBLE MANAGED BLOCK - K8S HOSTS"

    # Step 9: Add Kubernetes repository
    - name: Add kubernetes apt signing key
      become: true
      ansible.builtin.apt_key:
        state: "present"
        url: "https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key"

    - name: Add Kubernetes repository
      become: true
      ansible.builtin.apt_repository:
        repo: "deb https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
        state: present
        filename: kubernetes
        update_cache: true

    # Step 10: Install K8s tools
    - name: Install containerd and runc
      become: true
      ansible.builtin.apt:
        name:
          - containerd=1.7.24*
          - runc=1.1.12*
          - kubelet=1.32.4*
          - kubeadm=1.32.4*
          - kubectl=1.32.4*
        state: present

    - name: Hold packages
      become: true
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - containerd
        - runc
        - kubelet
        - kubeadm
        - kubectl

    # Step 11: Configure Containerd
    - name: Create containerd config directory
      become: true
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
        mode: "755"

    - name: Generate default containerd config
      become: true
      ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Disable AppArmor in containerd
      become: true
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^\s*disable_apparmor\s*='
        line: '    disable_apparmor = true'

    - name: Update sandbox image
      become: true
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^\s*sandbox_image\s*='
        line: '    sandbox_image = "registry.k8s.io/pause:3.10"'

    - name: Set SystemdCgroup
      become: true
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^\s*SystemdCgroup\s*='
        line: '            SystemdCgroup = true' # The indentation is intentional to match the file original format

    - name: Restart containerd
      become: true
      ansible.builtin.service:
        name: containerd
        state: restarted
        enabled: true

    # Step 12: Kubelet
    - name: Start and enable kubelet
      become: true
      ansible.builtin.service:
        name: kubelet
        state: started
        enabled: true
