apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.name }}-stable
  labels:
    app: {{ .Release.Name }}-{{ .Values.app.name }}
    version: stable
spec:
  replicas: {{ .Values.canary.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.app.name }}
      version: stable
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.app.name }}
        version: stable
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      volumes:
        - name: dummy-shared-volume
          hostPath:
            path: /mnt/shared
            type: Directory
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          ports:
            - containerPort: {{ .Values.app.port }}
              name: http
            {{- if and (hasKey .Values.app "metrics") .Values.app.metrics.enabled (ne .Values.app.metrics.port .Values.app.port) }}
            - containerPort: {{ .Values.app.metrics.port }}
              name: metrics
            {{- end }}
          env:
            - name: MODEL_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MODEL_HOST
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: APP_PORT
          volumeMounts:
            - name: dummy-shared-volume
              mountPath: /app/shared
