apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.app.name }}
      version: stable
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.app.name }}
        version: stable
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          ports:
            - containerPort: {{ .Values.app.port }}
              name: http
            {{- if and (hasKey .Values.app "metrics") .Values.app.metrics.enabled (ne .Values.app.metrics.port .Values.app.port) }}
            - containerPort: {{ .Values.app.metrics.port }}
              name: metrics
            {{- end }}
          env:
            - name: MODEL_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MODEL_HOST
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: APP_PORT
