{{- if .Values.shadow.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.model.name }}-shadow
  labels:
    app: {{ .Release.Name }}-{{ .Values.model.name }}-shadow
    version: shadow
spec:
  replicas: {{ .Values.shadow.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.model.name }}-shadow
      version: shadow
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.model.name }}-shadow
        version: shadow
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/componentLogLevel: "ext_authz:debug,filter:debug"
        proxy.istio.io/config: |
          proxyStatsMatcher:
            inclusionPrefixes:
              - "cluster"
              - "http"
          drainDuration: 45s
    spec:
      containers:
        - name: {{ .Values.model.name }}-shadow
          image: {{ .Values.shadow.modelImage | default .Values.model.image }}
          ports:
            - containerPort: {{ .Values.model.port }}
              name: http
          env:
            - name: MODEL_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MODEL_PORT
            - name: MODEL_URL
              value: "{{ .Values.shadow.modelUrl | default .Values.model.model_url }}"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: SHADOW_MODE
              value: "true"
{{- end }}

